# Generated by Django 2.1.7 on 2019-03-06 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190306_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinelist',
            name='location',
        ),
        migrations.RemoveField(
            model_name='dinelist',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='dinelist',
            name='participant',
        ),
        migrations.DeleteModel(
            name='DineList',
        ),
        migrations.DeleteModel(
            name='DineLocation',
        ),
    ]
