# Generated by Django 2.1.7 on 2019-03-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_dine', '0002_auto_20190306_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dine',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
