# Generated by Django 2.1.7 on 2019-03-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_dine', '0003_auto_20190308_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dine',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
