# Generated by Django 2.1.7 on 2019-03-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_dine', '0004_auto_20190308_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinelocation',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
